name: Build Blog

on:
  push:
    branches: dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: build
        run: |
          npm install
          git config --global user.email isagul3477@gmail.com
          git config --global user.name isagul
          npm run deploy
        env:
          CI: true
